import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    screenView: {
        flex: 1,
        // minHeight: 1000,
        width: '100%',
        backgroundColor: '#0B2E3F',
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft: 300,
    },
    screenTitle: {
        // flex: 1,
        padding: 18,
        fontSize: 24,
        color: '#F2F7F9',
        alignSelf: 'center',
        // backgroundColor: 'green',
    },
    sectionView: {
        flex: 4,
        margin: 18,
        padding: 18,
        // width: '100%',
        // width: 300,
        // height: 600,
        minWidth: 300,
        maxWidth: 600,
        backgroundColor: '#1F4B60',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        // justifyContent: 'center',
    },
    sectionText: {
        padding: 9,
        fontSize: 18,
        color: '#F2F7F9',
        // alignSelf: 'center',
    },
    button: {
        flex: 1,
        minHeight: 40,
        maxHeight: 40,
        minWidth: 80,
        maxWidth: 80,
        backgroundColor: '#3B6A82',
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'space-evenly',
        // margin: 9,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: "600",
        color: '#F2F7F9',
        alignSelf: 'center',
    },
    formField: {
        height: 40,
        width: 200,
        textAlign: 'center',
        color: '#031721',
        backgroundColor: '#F2F7F9',
        borderRadius: 4,
        marginBottom: 18,
    },
});