import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    screenView: {
        flex: 1,
        // minHeight: 1000,
        width: '100%',
        backgroundColor: '#0B2E3F',
        alignItems: 'center',
        justifyContent: 'center',
        // marginLeft: 300,
    },
    screenTitleContainer: {
        flex: 1,
        minHeight: 40,
        maxHeight: 40,
        minWidth: 200,
        maxWidth: 200,
        backgroundColor: '#031721',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
    },
    screenTitleText: {
        // flex: 1,
        // paddingVertical: 6,
        // paddingHorizontal: 18,
        fontSize: 24,
        color: '#F2F7F9',
        // alignSelf: 'center',
        // backgroundColor: 'green',
    },
    screenContentContainer: {
        flex: 9,
        maxWidth: 900,
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        // backgroundColor: 'red',
    },
    sectionView: {
        flex: 4,
        margin: 18,
        padding: 18,
        minHeight: 300,
        minWidth: 300,
        // maxWidth: 600,
        backgroundColor: '#1F4B60',
        alignItems: 'center',
        justifyContent: 'space-evenly',
        borderRadius: 10,
        // justifyContent: 'center',
    },
    sectionTitleContainer: {
        flex: 2,
        minHeight: 50,
        maxHeight: 50,
        minWidth: 200,
        maxWidth: 200,
        backgroundColor: '#0B2E3F',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    sectionTitleText: {
        fontSize: 20,
        // maxHeight: 80,
        // minWidth: 160,
        // textAlign: 'center',
        color: '#F2F7F9',
    },
    sectionContentContainer: {
        flex: 8,
        alignItems: 'center',
        justifyContent: 'space-evenly',
    },
    sectionText: {
        // flex: 1,
        // padding: 9,
        fontSize: 18,
        color: '#F2F7F9',
        // alignSelf: 'center',
    },
    buttonFA: {
        flex: 1,
        minHeight: 40,
        maxHeight: 40,
        minWidth: 40,
        maxWidth: 40,
        backgroundColor: '#3B6A82',
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconFA: {
        color: '#F2F7F9',
    },
    button: {
        flex: 1,
        minHeight: 40,
        maxHeight: 40,
        minWidth: 80,
        maxWidth: 80,
        backgroundColor: '#3B6A82',
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'space-evenly',
        // margin: 9,
    },
    buttonText: {
        fontSize: 16,
        fontWeight: "600",
        color: '#F2F7F9',
        alignSelf: 'center',
    },
    formField: {
        // flex: 1,
        height: 40,
        width: 200,
        textAlign: 'center',
        color: '#031721',
        backgroundColor: '#F2F7F9',
        borderRadius: 4,
        marginBottom: 18,
    },
});